# Generated by Django 2.1.2 on 2019-04-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_cart_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cart',
            new_name='CartItem',
        ),
    ]
