# Generated by Django 2.1.2 on 2019-05-02 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0005_auto_20190501_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 2, 20, 6, 49, 608123)),
        ),
    ]
