# Generated by Django 2.1.2 on 2019-05-03 07:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0012_auto_20190503_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_link',
            field=models.URLField(default='www.google.com'),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 13, 19, 57, 284288)),
        ),
    ]
