# Generated by Django 2.1.2 on 2019-05-03 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0013_auto_20190503_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 3, 13, 20, 3, 319263)),
        ),
    ]
